# Generated by Django 3.2.4 on 2021-06-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.nutrition'),
        ),
    ]
