# Generated by Django 3.2.4 on 2021-06-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210619_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergys',
        ),
    ]
