# Generated by Django 3.2.4 on 2021-06-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_allergys'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergies',
            field=models.ManyToManyField(to='products.Allergy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.nutrition'),
        ),
        migrations.DeleteModel(
            name='ProductAllergy',
        ),
    ]
